import dotenv from 'dotenv';
dotenv.config();



const CONSUMER = {
     CONSUMER_SIGNUP: "PRODUCER_SIGNUP_FROM_API",
     VERIFICATION_FROM_API_TO_AUTH: "VERIFICATION_FROM_API_TO_AUTH",
     VERIFICATION_OTP_FROM_API_TO_AUTH: "VERIFICATION_OTP_FROM_API_TO_AUTH",
     REQUEST_VERIFICATION_FROM_API_TO_AUTH: "REQUEST_VERIFICATION_FROM_API_TO_AUTH",
     FORGOT_PASSWORD_FROM_API_TO_AUTH: "FORGOT_PASSWORD_FROM_API_TO_AUTH",
     RESET_PASSWORD_FROM_API_TO_AUTH: "RESET_PASSWORD_FROM_API_TO_AUTH",
     LOGIN_FROM_API_TO_AUTH: "LOGIN_FROM_API_TO_AUTH",
     REQUEST_REFRESH_TOKEN_FROM_API_TO_AUTH: "REQUEST_REFRESH_TOKEN_FROM_API_TO_AUTH",
     CHANGE_PASSWORD_FROM_API_TO_AUTH: "CHANGE_PASSWORD_FROM_API_TO_AUTH",
     UPDATE_PROFILE_FROM_API_TO_AUTH: "UPDATE_PROFILE_FROM_API_TO_AUTH",
     CHANGE_EMAIL_FROM_API_TO_AUTH: "CHANGE_EMAIL_FROM_API_TO_AUTH",
     VERIFY_CHANGE_EMAIL_FROM_API_TO_AUTH: "VERIFY_CHANGE_EMAIL_FROM_API_TO_AUTH",
     GET_USER_FROM_API_TO_AUTH: "GET_USER_FROM_API_TO_AUTH",
     DEL_USER_FROM_API_TO_AUTH: "DEL_USER_FROM_API_TO_AUTH",
     SUSPENDED_USER_FROM_API_TO_AUTH: "SUSPENDED_USER_FROM_API_TO_AUTH",
     UNSUSPENDED_USER_FROM_API_TO_AUTH: "UNSUSPENDED_USER_FROM_API_TO_AUTH",
     ALL_USER_FROM_API_TO_AUTH: "ALL_USER_FROM_API_TO_AUTH",
     LOGOUT_FROM_API_TO_AUTH: "LOGOUT_FROM_API_TO_AUTH",
     SET_AVATAR_FROM_API_TO_AUTH: "SET_AVATAR_FROM_API_TO_AUTH",
     USERNAME_FROM_API_TO_AUTH: "USERNAME_FROM_API_TO_AUTH",
     FOLLOW_TOPIC: "FOLLOW_TOPIC",
     UNFOLLOW_TOPIC: "UNFOLLOW_TOPIC",
     GET_ALL_FOLLOW_TOPIC: "GET_ALL_FOLLOW_TOPIC",
     GET_ALL_FOLLOWING_TOPIC: "GET_ALL_FOLLOWING_TOPIC",
     CREATE_TWEET_TOPIC: "CREATE_TWEET_TOPIC",
     DELETE_TWEET_TOPIC: "DELETE_TWEET_TOPIC",
}

const PRODUCER = {
     PRODUCER_SIGNUP_NODEMAILER: "PRODUCER_SIGNUP_NODEMAILER",
     RESPONSE_FROM_AUTH_SERVICE: "RESPONSE_FROM_AUTH_SERVICE",
     RESPONSE_VERIFICATION_EMAIL_FROM_AUTH: "RESPONSE_VERIFICATION_EMAIL_FROM_AUTH",
     RESPONSE_VERIFICATION_OTP_FROM_API_TO_AUTH: "RESPONSE_VERIFICATION_OTP_FROM_API_TO_AUTH",
     RESPONSE_REQUEST_VERIFICATION: "RESPONSE_REQUEST_VERIFICATION",
     PRODUCER_SIGNUP_NODEMAILER_REQUEST_VERIFICATION: "PRODUCER_SIGNUP_NODEMAILER_REQUEST_VERIFICATION",
     RESPONSE_FORGOT_PASSWORD: "RESPONSE_FORGOT_PASSWORD",
     FORGOT_PASSWORD_NODEMAILER: "FORGOT_PASSWORD_NODEMAILER",
     RESPONSE_RESET_PASSWORD: "RESPONSE_RESET_PASSWORD",
     RESPONSE_LOGIN: "RESPONSE_LOGIN",
     RESPONSE_REQUEST_ACCESSTOKEN: "RESPONSE_REQUEST_ACCESSTOKEN",
     RESPONSE_CHANGE_PASSWORD: "RESPONSE_CHANGE_PASSWORD",
     RESPONSE_UPDATE_PROFILE: "RESPONSE_UPDATE_PROFILE",
     RESPONSE_CHANGE_EMAIL: "RESPONSE_CHANGE_EMAIL",
     CHANGE_EMAIL_NODEMAILER: "CHANGE_EMAIL_NODEMAILER",
     RESPONSE_VERIFY_CHANGE_EMAIL: "RESPONSE_VERIFY_CHANGE_EMAIL",
     RESPONSE_GET_USER: "RESPONSE_GET_USER",
     RESPONSE_DEL_USER: "RESPONSE_DEL_USER",
     RESPONSE_SUSPENDED_USER: "RESPONSE_SUSPENDED_USER",
     RESPONSE_SUSPENDED_USER_NODEMAILER: "RESPONSE_SUSPENDED_USER_NODEMAILER",
     RESPONSE_UNSUSPENDED_USER_NODEMAILER: "RESPONSE_UNSUSPENDED_USER_NODEMAILER",
     RESPONSE_UNSUSPENDED_USER: "RESPONSE_UNSUSPENDED_USER",
     RESPONSE_ALL_USER: "RESPONSE_ALL_USER",
     RESPONSE_LOGOUT: "RESPONSE_LOGOUT",
     RESPONSE_SET_AVATAR: "RESPONSE_SET_AVATAR",
     RESPONSE_USERNAME: "RESPONSE_USERNAME",
     RESPONSE_TWEET_TOPIC: "RESPONSE_TWEET_TOPIC",
     RESPONSE_DELETE_TWEET_TOPIC: "RESPONSE_DELETE_TWEET_TOPIC",

     /////////
     
     RESPONSE_FOLLOW_TOPIC: "RESPONSE_FOLLOW_TOPIC",
     FOLLOW_USER_SERVICES: "FOLLOW_USER_SERVICES",
     RESPONSE_UNFOLLOW_TOPIC: "RESPONSE_UNFOLLOW_TOPIC",
     UNFOLLOW_USER_SERVICES: "UNFOLLOW_USER_SERVICES",
     RESPONSE_ALL_FOLLOW_TOPIC: "RESPONSE_ALL_FOLLOW_TOPIC",
     ALL_FOLLOW_USER_SERVICES: "ALL_FOLLOW_USER_SERVICES",
     RESPONSE_ALL_FOLLOWING_TOPIC: "RESPONSE_ALL_FOLLOWING_TOPIC",
     ALL_FOLLOWING_USER_SERVICES: "ALL_FOLLOWING_USER_SERVICES",
     TWEET_TOPIC_SERVICES: "TWEET_TOPIC_SERVICES",
     DELETE_TWEET_TOPIC_SERVICES: "DELETE_TWEET_TOPIC_SERVICES",


     /////////
     CREATE_FOLLOW_TOPIC: "CREATE_FOLLOW_TOPIC",


     
}

export {
     CONSUMER,
     PRODUCER
}