import dotenv from 'dotenv';
dotenv.config();



const PRODUCER = {
     PRODUCER_SIGNUP: "PRODUCER_SIGNUP_FROM_API",
     VERIFICATION_FROM_API_TO_AUTH: "VERIFICATION_FROM_API_TO_AUTH",
     VERIFICATION_OTP_FROM_API_TO_AUTH: "VERIFICATION_OTP_FROM_API_TO_AUTH",
     REQUEST_VERIFICATION_FROM_API_TO_AUTH: "REQUEST_VERIFICATION_FROM_API_TO_AUTH",
     FORGOT_PASSWORD_FROM_API_TO_AUTH: "FORGOT_PASSWORD_FROM_API_TO_AUTH",
     RESET_PASSWORD_FROM_API_TO_AUTH: "RESET_PASSWORD_FROM_API_TO_AUTH",
     LOGIN_FROM_API_TO_AUTH: "LOGIN_FROM_API_TO_AUTH",
     REQUEST_REFRESH_TOKEN_FROM_API_TO_AUTH: "REQUEST_REFRESH_TOKEN_FROM_API_TO_AUTH",
     CHANGE_PASSWORD_FROM_API_TO_AUTH: "CHANGE_PASSWORD_FROM_API_TO_AUTH",
     UPDATE_PROFILE_FROM_API_TO_AUTH: "UPDATE_PROFILE_FROM_API_TO_AUTH",
     CHANGE_EMAIL_FROM_API_TO_AUTH: "CHANGE_EMAIL_FROM_API_TO_AUTH",
     VERIFY_CHANGE_EMAIL_FROM_API_TO_AUTH: "VERIFY_CHANGE_EMAIL_FROM_API_TO_AUTH",
     GET_USER_FROM_API_TO_AUTH: "GET_USER_FROM_API_TO_AUTH",
     DEL_USER_FROM_API_TO_AUTH: "DEL_USER_FROM_API_TO_AUTH",
     SUSPENDED_USER_FROM_API_TO_AUTH: "SUSPENDED_USER_FROM_API_TO_AUTH",
     UNSUSPENDED_USER_FROM_API_TO_AUTH: "UNSUSPENDED_USER_FROM_API_TO_AUTH",
     ALL_USER_FROM_API_TO_AUTH: "ALL_USER_FROM_API_TO_AUTH",
     LOGOUT_FROM_API_TO_AUTH: "LOGOUT_FROM_API_TO_AUTH",
     SET_AVATAR_FROM_API_TO_AUTH: "SET_AVATAR_FROM_API_TO_AUTH",
     USERNAME_FROM_API_TO_AUTH: "USERNAME_FROM_API_TO_AUTH",



}

const PRODUCER_FOLLOW = {
     FOLLOW_TOPIC: "FOLLOW_TOPIC",
     UNFOLLOW_TOPIC: "UNFOLLOW_TOPIC",
     GET_ALL_FOLLOW_TOPIC: "GET_ALL_FOLLOW_TOPIC",
     GET_ALL_FOLLOWING_TOPIC: "GET_ALL_FOLLOWING_TOPIC",
     unLIKE_TWEET_TOPIC: "unLIKE_TWEET_TOPIC",
}

const PRODUCER_TWEET = {
     CREATE_TWEET_TOPIC: "CREATE_TWEET_TOPIC",
     DELETE_TWEET_TOPIC_SERVICES: "DELETE_TWEET_TOPIC_SERVICES",
     EDIT_TWEET_TOPIC: "EDIT_TWEET_TOPIC",
     CHECK_TWEET: "CHECK_TWEET",
     RETWEET_TOPIC: "RETWEET_TOPIC",
     UNRETWEET_TOPIC: "UNRETWEET_TOPIC",
     CHECK_TWEET_TOPIC: "CHECK_TWEET_TOPIC",
     CHECK_RETWEET_TOPIC_FOR_COMMENT: "CHECK_RETWEET_TOPIC_FOR_COMMENT",
     COMMENT_TWEET_TOPIC: "COMMENT_TWEET_TOPIC",
     GET_COMMENT_TOPIC: "GET_COMMENT_TOPIC",
     DEL_COMMENT_TOPIC: "DEL_COMMENT_TOPIC",
     EDIT_COMMENT_TOPIC: "EDIT_COMMENT_TOPIC",
     GET_ALL_COMMENT_TOPIC: "GET_ALL_COMMENT_TOPIC",
     GET_TWEET_TOPIC: "GET_TWEET_TOPIC",
     NAV_TWEET_TOPIC: "NAV_TWEET_TOPIC",
     CHECK_TWEET_FOR_COMMENT_TOPIC: "CHECK_TWEET_FOR_COMMENT_TOPIC",
     CHECK_TWEET_GET_COMMENT_TOPIC: "CHECK_TWEET_GET_COMMENT_TOPIC",


}

const CONSUMER = {
     RESPONSE_FROM_AUTH_SERVICE: "RESPONSE_FROM_AUTH_SERVICE",
     RESPONSE_VERIFICATION_EMAIL_FROM_AUTH: "RESPONSE_VERIFICATION_EMAIL_FROM_AUTH",
     RESPONSE_VERIFICATION_OTP_FROM_API_TO_AUTH: "RESPONSE_VERIFICATION_OTP_FROM_API_TO_AUTH",
     RESPONSE_REQUEST_VERIFICATION: "RESPONSE_REQUEST_VERIFICATION",
     RESPONSE_FORGOT_PASSWORD: "RESPONSE_FORGOT_PASSWORD",
     RESPONSE_RESET_PASSWORD: "RESPONSE_RESET_PASSWORD",
     RESPONSE_LOGIN: "RESPONSE_LOGIN",
     RESPONSE_REQUEST_ACCESSTOKEN: "RESPONSE_REQUEST_ACCESSTOKEN",
     RESPONSE_CHANGE_PASSWORD: "RESPONSE_CHANGE_PASSWORD",
     RESPONSE_UPDATE_PROFILE: "RESPONSE_UPDATE_PROFILE",
     RESPONSE_CHANGE_EMAIL: "RESPONSE_CHANGE_EMAIL",
     RESPONSE_VERIFY_CHANGE_EMAIL: "RESPONSE_VERIFY_CHANGE_EMAIL",
     RESPONSE_GET_USER: "RESPONSE_GET_USER",
     RESPONSE_DEL_USER: "RESPONSE_DEL_USER",
     RESPONSE_SUSPENDED_USER: "RESPONSE_SUSPENDED_USER",
     RESPONSE_UNSUSPENDED_USER: "RESPONSE_UNSUSPENDED_USER",
     RESPONSE_ALL_USER: "RESPONSE_ALL_USER",
     RESPONSE_LOGOUT: "RESPONSE_LOGOUT",
     RESPONSE_SET_AVATAR: "RESPONSE_SET_AVATAR",
     RESPONSE_USERNAME: "RESPONSE_USERNAME",
     RESPONSE_FOLLOW_TOPIC: "RESPONSE_FOLLOW_TOPIC",
     RESPONSE_UNFOLLOW_TOPIC: "RESPONSE_UNFOLLOW_TOPIC",
     RESPONSE_ALL_FOLLOW_TOPIC: "RESPONSE_ALL_FOLLOW_TOPIC",
     RESPONSE_ALL_FOLLOWING_TOPIC: "RESPONSE_ALL_FOLLOWING_TOPIC",
     RESPONSE_TWEET_TOPIC: "RESPONSE_TWEET_TOPIC",
     RESPONSE_DELETE_TWEET_TOPIC: "RESPONSE_DELETE_TWEET_TOPIC",
     RESPONSE_CHECK_TWEET: "RESPONSE_CHECK_TWEET",
     RESPONSE_RETWEET_TOPIC: "RESPONSE_RETWEET_TOPIC",
     REPONSE_UNRETWEET_TOPIC: "REPONSE_UNRETWEET_TOPIC",
     REPONSE_LIKE_TOPIC: "REPONSE_LIKE_TOPIC",
     REPONSE_UNLIKE_TOPIC: "REPONSE_UNLIKE_TOPIC",
     REPONSE_COMMENT_TOPIC: "REPONSE_COMMENT_TOPIC",
     RESPONSE_GET_COMMENT_TOPIC: "RESPONSE_GET_COMMENT_TOPIC",
     RESPONSE_DEL_COMMENT_TOPIC: "RESPONSE_DEL_COMMENT_TOPIC",
     RESPONSE_EDIT_COMMENT_TOPIC: "RESPONSE_EDIT_COMMENT_TOPIC",
     RESPONSE_ALL_COMMENT_TWEET_TOPIC: "RESPONSE_ALL_COMMENT_TWEET_TOPIC",
     RESPONSE_GET_TWEET_ID: "RESPONSE_GET_TWEET_ID",
     RESPONSE_NAV_PAGE: "RESPONSE_NAV_PAGE",
}


export {
     PRODUCER,
     CONSUMER,
     PRODUCER_FOLLOW,
     PRODUCER_TWEET
}