import dotenv from 'dotenv';
dotenv.config();



const CONSUMER = {

     TWEET_OK: "TWEET_OK",
     unLIKE_TWEET_TOPIC: "unLIKE_TWEET_TOPIC",
     COMMENT_TWEET_TOPIC: "COMMENT_TWEET_TOPIC",
     GET_COMMENT_TOPIC: "GET_COMMENT_TOPIC",
     DEL_COMMENT_TOPIC: "DEL_COMMENT_TOPIC",
     EDIT_COMMENT_TOPIC: "EDIT_COMMENT_TOPIC",
     GET_ALL_COMMENT_TOPIC: "GET_ALL_COMMENT_TOPIC",
     DEL_INTERACT: "DEL_INTERACT",

}



export {
     CONSUMER,

}