

import dotenv from 'dotenv';  
dotenv.config();



const COMSUMER_TOPIC = {
     PRODUCER_SIGNUP_NODEMAILER: "PRODUCER_SIGNUP_NODEMAILER",
     PRODUCER_SIGNUP_NODEMAILER_REQUEST_VERIFICATION: "PRODUCER_SIGNUP_NODEMAILER_REQUEST_VERIFICATION",
     FORGOT_PASSWORD_NODEMAILER: "FORGOT_PASSWORD_NODEMAILER",
     CHANGE_EMAIL_NODEMAILER: "CHANGE_EMAIL_NODEMAILER",
     RESPONSE_SUSPENDED_USER_NODEMAILER: "RESPONSE_SUSPENDED_USER_NODEMAILER",
     RESPONSE_UNSUSPENDED_USER_NODEMAILER: "RESPONSE_UNSUSPENDED_USER_NODEMAILER"
}

export {
     COMSUMER_TOPIC
}