import dotenv from 'dotenv';
dotenv.config();



const CONSUMER = {
     FOLLOW_USER_SERVICES: "FOLLOW_USER_SERVICES",
     UNFOLLOW_USER_SERVICES: "UNFOLLOW_USER_SERVICES",
     ALL_FOLLOW_USER_SERVICES: "ALL_FOLLOW_USER_SERVICES",
     ALL_FOLLOWING_USER_SERVICES: "ALL_FOLLOWING_USER_SERVICES",
     CREATE_FOLLOW_TOPIC: "CREATE_FOLLOW_TOPIC",
     DEL_ACCOUNT_TOPIC: "DEL_ACCOUNT_TOPIC",
}


export {
     CONSUMER,

}