import dotenv from 'dotenv';
dotenv.config();



const CONSUMER = {

     TWEET_TOPIC_SERVICES: "TWEET_TOPIC_SERVICES",
     DELETE_TWEET_TOPIC_SERVICES: "DELETE_TWEET_TOPIC_SERVICES",
     CHECK_TWEET: "CHECK_TWEET",
     EDIT_TWEET_TOPIC: "EDIT_TWEET_TOPIC",
     RESPONSE_CHECK_TWEET: "RESPONSE_CHECK_TWEET",
     CREATE_TWEET_TOPIC: "CREATE_TWEET_TOPIC",
     RESPONSE_TWEET_TOPIC: "RESPONSE_TWEET_TOPIC",
     RETWEET_TOPIC: "RETWEET_TOPIC",
     UNRETWEET_TOPIC: "UNRETWEET_TOPIC",
     CHECK_TWEET_TOPIC: "CHECK_TWEET_TOPIC",
     GET_TWEET_TOPIC: "GET_TWEET_TOPIC",
     NAV_TWEET_TOPIC: "NAV_TWEET_TOPIC",
     CHECK_TWEET_FOR_COMMENT_TOPIC: "CHECK_TWEET_FOR_COMMENT_TOPIC",
     CHECK_TWEET_GET_COMMENT_TOPIC: "CHECK_TWEET_GET_COMMENT_TOPIC",

}



export {
     CONSUMER,

}